[tool.mypy]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
strict = true

[tool.ruff]
select = [
    # pyflakes
    "F",
    # pycodestyle errors, warnings
    "E",
    "W",
    # isort
    "I",
    # flake8-2020
    "YTT",
    # flake8-bugbear
    "B",
]
line-length = 120
target-version = "py311"

[tool.black]
line-length = 120
target-version = ["py311"]
